POST http://localhost:3000/orders
Content-Type: application/json

{
    "customerId": "1",
    "itens": [
        {
            "productId": "1",
            "quantity": 1,
            "unitPrice": 100
        },
        {
            "productId": "2",
            "quantity": 1,
            "unitPrice": 50
        }
    ],
    "payment": {
        "method": "CREDIT_CARD",
        "installment": 1
    },
    "delivery": {
        "addressId": "1"
    }
}

